# Generated by Django 4.2.4 on 2023-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_music', '0003_remove_song_audio_file_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
